# Generated by Django 5.0.4 on 2024-12-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_budget_budget_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='amount',
        ),
    ]
